# Generated by Django 5.0.6 on 2024-05-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutitem/')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('aboutItem', models.ManyToManyField(to='indico.aboutitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
